#!/usr/bin/env bash
# Script to configure nginix server
#cd "~"
apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
apt-get -y  install curl
mkdir -p /var/www/html
chown -R $USER:$USER /var/www
chmod -R 755 /var/www
# Create the HTML file
#echo "<html>
#  <head>
#    <title>Welcome to nginx!</title>
#  </head>
#  <body>
#    <h1>Hello World!</h1>
#  </body>
#</html>" > /var/www/html/index.html

echo "Hello World!" > /var/www/html/index.html


# | sudo tee /var/www/html/index.html

# Restart Nginx to apply changes (without using systemctl)
nginx -s reload

# Ensure Nginx is running
service nginx start

# Output the status of the Nginx service
service nginx status
