#!/usr/bin/env bash
# Configuring load Balncer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg 


echo "
frontend lb
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 220602-web-01 54.160.101.222:80 check
    server 220602-web-02 100.25.205.48:80 check" >> /etc/haproxy/haproxy.cfg


sudo service haproxy retart
