#!/usr/bin/env bash
# Configuring load Balncer
sudo apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-3.0
apt-get -y install haproxy=3.0.\*

cp /etc/haproxy/haproxy.cfg cp /etc/haproxy/haproxy.cfg.backup."$(date +%Y%m%d%H%M%S)"

# echo "frontend http \\n\\\tbind *:80\\n\\\tmode http\\n\\n\\n\\\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg
# echo "backend web-backend \\n\\\tbalance roundrobin\n\\tserver web-01 54.160.101.222:80 check\n\\tserver web-02 100.25.205.48:80 check\n"

cat <<EOL | sudo tee -a /etc/haproxy/haproxy.cfg

frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server web-01 54.160.101.222:80 check
    server web-02 100.25.205.48:80 check
EOL


sudo systemctl enable haproxy
sudo systemctl start haproxy

# Verify HAProxy status
sudo systemctl status haproxy
