#!/usr/bin/env bash
# Script to create user
sudo mysql -e "CREATE USER 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';"
sudo mysql -e "GRANT REPLICATION CLIENT on *.* TO 'holberton_user'@'localhost'"
