#!/usr/bin/env bash

# This script tells a story about each user in /etc/passwd using the while loop + IFS

while IFS=':' read -r username x uid gid comment home shell; do
  passcode=$(sudo grep "^$username:" /etc/shadow | cut -d':' -f2)
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $comment"
done < /etc/passwd
