#!/usr/bin/env bash
# This script configures an Ubuntu server to meet specific IP resolution requirements.

# Modify /etc/hosts to change IP resolutions
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
sudo sh -c 'echo "8.8.8.8	facebook.com" >> /etc/hosts'
